//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingPayment
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string UserPhone { get; set; }
        public string SubscriptionType { get; set; }
        public Nullable<bool> IsStorageSubscription { get; set; }
        public Nullable<bool> IsReceivedCommissions { get; set; }
        public Nullable<System.DateTime> SubscriptionExpiredOn { get; set; }
        public Nullable<System.DateTime> StorageExpiredOn { get; set; }
        public string YTD_Contact_Export_Limit { get; set; }
        public string MTD_Contact_Import_Limit { get; set; }
        public string Contact_Storage_Limit { get; set; }
        public Nullable<bool> IsBillingCycleMonthly { get; set; }
        public Nullable<bool> IsBillingComplete { get; set; }
        public Nullable<System.DateTime> ReferralStartDate { get; set; }
        public Nullable<System.DateTime> ReferralEndDate { get; set; }
        public Nullable<bool> IsCommissionMonthly { get; set; }
        public string YTD_Commission { get; set; }
        public string MTD_Commission { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string YTD_ReferralUser { get; set; }
        public string Total_ReferralUser { get; set; }
        public Nullable<System.DateTime> ReferralRecycleDate { get; set; }
        public Nullable<System.DateTime> LastReferralCalculatedDate { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public string BasicAmount { get; set; }
        public string StorageAmount { get; set; }
        public string SubTotalCharge { get; set; }
        public string Promocode { get; set; }
        public string DiscountPercentage { get; set; }
        public string Discount { get; set; }
        public string GrossAmount { get; set; }
        public string CheckingAccountProcessingFee { get; set; }
        public string NetAmount { get; set; }
        public string NoOfContact { get; set; }
        public string ContactMultiplier { get; set; }
        public string TotalContact { get; set; }
        public string PerUnitCharge { get; set; }
        public string MonthlyCharge { get; set; }
        public Nullable<bool> IsAgree { get; set; }
    }
}
