//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInformation
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExt { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Category { get; set; }
        public string ProfileLogo { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> IsOverwrite { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserTypeContact { get; set; }
        public string Other { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RefPhone { get; set; }
        public string Title { get; set; }
        public string TypeOfContact { get; set; }
        public string Memo { get; set; }
        public string CountryCode { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<short> IsEmailFlow { get; set; }
    }
}
