//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_SalesPartner
    {
        public int id { get; set; }
        public string serialCode { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string stateId { get; set; }
        public string countryId { get; set; }
        public string region { get; set; }
        public string zipCode { get; set; }
        public string primaryPhoneNo { get; set; }
        public string mobilePhoneNo { get; set; }
        public string routingNo { get; set; }
        public string accountNo { get; set; }
        public string email { get; set; }
        public Nullable<int> userType { get; set; }
        public Nullable<System.DateTime> joinDate { get; set; }
        public Nullable<decimal> commissionRate { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
