//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_SalesPartner_DetailsZipCodeCoverage
    {
        public int id { get; set; }
        public string dealerSalesPartnerId { get; set; }
        public string zipCode { get; set; }
        public Nullable<decimal> commissionRate { get; set; }
    }
}
