//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSchedule
    {
        public int Id { get; set; }
        public string PersonName { get; set; }
        public string PersonEmail { get; set; }
        public string FromEmail { get; set; }
        public Nullable<bool> IsLoop { get; set; }
        public string Days { get; set; }
        public Nullable<bool> IsZeroMailSent { get; set; }
        public Nullable<System.DateTime> ZeroEmailSentOn { get; set; }
        public Nullable<int> LastEmailNumber { get; set; }
        public Nullable<System.DateTime> LastEmailSentOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
    }
}
