//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailUnsubscribe
    {
        public long Id { get; set; }
        public string TemplateNo { get; set; }
        public string UserId { get; set; }
        public string TemplateId { get; set; }
    }
}
