//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int Id { get; set; }
        public string PersonEmail { get; set; }
        public string FromEmail { get; set; }
        public Nullable<int> EmailNumber { get; set; }
        public Nullable<System.DateTime> EmailSentOn { get; set; }
        public string Status { get; set; }
        public string TemplateId { get; set; }
    }
}
