//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialTransaction
    {
        public long Id { get; set; }
        public string Serial { get; set; }
        public string AccountType { get; set; }
        public string LedgerCode { get; set; }
        public string InvoiceNo { get; set; }
        public string RefId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Remarks { get; set; }
        public string EntryType { get; set; }
    }
}
