//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalID
    {
        public string ObjectID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> IDForYear { get; set; }
        public Nullable<int> IDForMonth { get; set; }
        public Nullable<System.DateTime> IDForDate { get; set; }
        public int CurrentID { get; set; }
    }
}
