//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public long Id { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
        public Nullable<int> FromUserType { get; set; }
        public Nullable<int> ToUserType { get; set; }
        public string AccountName { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CardNumber { get; set; }
        public string CVS { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string LastFourDigitCard { get; set; }
        public Nullable<bool> IsCheckingAccount { get; set; }
        public string RoutingNo { get; set; }
        public string AccountNo { get; set; }
        public string CheckNo { get; set; }
        public string AccountType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string AuthorizationCode { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionDescription { get; set; }
        public string Getway { get; set; }
        public string Status { get; set; }
        public string Serial { get; set; }
        public string TransactionType { get; set; }
        public string LedgerCode { get; set; }
        public string Remarks { get; set; }
        public string SubscriptionType { get; set; }
        public Nullable<bool> IsStorageSubscription { get; set; }
        public Nullable<bool> IsReceivedCommissions { get; set; }
        public string YTD_Commission { get; set; }
        public string MTD_Commission { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public string YTD_Contact_Export_Limit { get; set; }
        public string MTD_Contact_Import_Limit { get; set; }
        public string Contact_Storage_Limit { get; set; }
        public Nullable<bool> IsBillingCycleMonthly { get; set; }
        public string BasicAmount { get; set; }
        public string StorageAmount { get; set; }
        public string SubTotalCharge { get; set; }
        public string Promocode { get; set; }
        public string DiscountPercentage { get; set; }
        public string Discount { get; set; }
        public string CheckingAccountProcessingFee { get; set; }
        public string GrossAmount { get; set; }
        public string NetAmount { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string NoOfContact { get; set; }
        public string ContactMultiplier { get; set; }
        public string TotalContact { get; set; }
        public string PerUnitCharge { get; set; }
        public string MonthlyCharge { get; set; }
        public Nullable<bool> IsAgree { get; set; }
    }
}
