//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class rat_transaction
    {
        public long Id { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public string filepath { get; set; }
    }
}
