//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralAccount
    {
        public int Id { get; set; }
        public string GiverPhone { get; set; }
        public string GetterPhone { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string YTD_Commission { get; set; }
        public string MTD_Commission { get; set; }
        public string YTD_CommissionOwed { get; set; }
        public string MTD_CommissionOwed { get; set; }
        public string YTD_CommissionPaid { get; set; }
        public string MTD_CommissionPaid { get; set; }
        public Nullable<System.DateTime> LastTransactionDate { get; set; }
    }
}
