//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralTransaction
    {
        public long Id { get; set; }
        public string GiverPhone { get; set; }
        public string GetterPhone { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> PayorAmount { get; set; }
        public string Description { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CommissionMonthDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string CommissionFor { get; set; }
        public string ZipCode { get; set; }
    }
}
