//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class States
    {
        public string STATE { get; set; }
        public string STATENAME { get; set; }
        public Nullable<decimal> SalesTaxRate { get; set; }
        public string FreightTaxable { get; set; }
        public Nullable<decimal> ShippingSurcharge { get; set; }
    }
}
