//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemInformation
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Website { get; set; }
        public string EmailServer1 { get; set; }
        public string EmailUser1 { get; set; }
        public string EmailPassword1 { get; set; }
        public string EmailServer2 { get; set; }
        public string EmailUser2 { get; set; }
        public string EmailPassword2 { get; set; }
        public string EmailServer3 { get; set; }
        public string EmailUser3 { get; set; }
        public string EmailPassword3 { get; set; }
        public string EmailServer4 { get; set; }
        public string EmailUser4 { get; set; }
        public string EmailPassword4 { get; set; }
        public string SecurityLink { get; set; }
        public string SecurityKey { get; set; }
        public string SecurityUser { get; set; }
        public string SecurityPassword { get; set; }
        public string CreditCardLink { get; set; }
        public string CreditCardKey { get; set; }
        public string CreditCardUser { get; set; }
        public string CreditCardPassword { get; set; }
        public string DocumentLink { get; set; }
        public Nullable<decimal> ApplicationFee { get; set; }
        public Nullable<short> FeeType { get; set; }
        public Nullable<decimal> FeePercentage { get; set; }
        public Nullable<decimal> FeeFlatAmount { get; set; }
        public Nullable<bool> IncludeProcessFees { get; set; }
        public Nullable<bool> TanentPayFees { get; set; }
        public Nullable<decimal> CreditCardProcessFees { get; set; }
        public Nullable<bool> OneTimePay { get; set; }
        public Nullable<bool> RecurringPay { get; set; }
        public Nullable<bool> IsGlobalSystem { get; set; }
        public Nullable<short> FeeTypeCheck { get; set; }
        public Nullable<decimal> FeePercentageCheck { get; set; }
        public Nullable<decimal> FeeFlatAmountCheck { get; set; }
    }
}
