//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Serial { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string PhoneVerifyCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string ProfileLogo { get; set; }
        public string CompanyName { get; set; }
        public string CompanyLogo { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExt { get; set; }
        public string Fax { get; set; }
        public Nullable<bool> IsPhoneVerified { get; set; }
        public Nullable<bool> IsNewUser { get; set; }
        public Nullable<bool> IsAgree { get; set; }
        public Nullable<bool> DoNotEmbedProfile { get; set; }
        public Nullable<bool> DoNotEmbedCompany { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Other { get; set; }
        public string DatabaseName { get; set; }
        public string DatabaseLocation { get; set; }
        public string UserTypeContact { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> CanLogin { get; set; }
        public Nullable<bool> IsUserProfileComplete { get; set; }
        public Nullable<bool> IsBillingComplete { get; set; }
        public Nullable<bool> IsOverwrite { get; set; }
        public string Website { get; set; }
        public string Category { get; set; }
        public string YTD_Contact_Export_Limit { get; set; }
        public string YTD_Contact_Export { get; set; }
        public string MTD_Contact_Import { get; set; }
        public string MTD_Contact_Import_Limit { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RefPhone { get; set; }
        public string Title { get; set; }
        public string TypeOfContact { get; set; }
        public string SubscriptionType { get; set; }
        public Nullable<System.DateTime> SubscriptionExpiredOn { get; set; }
        public Nullable<System.DateTime> StorageExpiredOn { get; set; }
        public Nullable<bool> IsStorageSubscription { get; set; }
        public Nullable<System.DateTime> LastImportedDate { get; set; }
        public Nullable<System.DateTime> LastExportedDate { get; set; }
        public string Contact_Storage_Limit { get; set; }
        public Nullable<bool> IsSentMail { get; set; }
        public string CountryCode { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<bool> IsEmailFlow { get; set; }
        public Nullable<System.DateTime> EmailFlowCreatedOn { get; set; }
    }
}
