//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagService.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPricing
    {
        public int Id { get; set; }
        public string UserPlans { get; set; }
        public Nullable<decimal> MonthlyCosts { get; set; }
        public string Billed { get; set; }
        public string ContactsImportsMonthly { get; set; }
        public string ContactExportsYearly { get; set; }
        public string StoredContacts { get; set; }
        public string Contacts_500 { get; set; }
        public string Contacts_10000 { get; set; }
        public Nullable<bool> ReferralCommissions { get; set; }
        public Nullable<bool> eTag365NFCChip { get; set; }
    }
}
